### ISSUE TITLE
Manjaro 在笔记本上的多显示器配置 | 左手的世界

### ISSUE THREAD

**Issue by AmazingRise** [AmazingRise/amazingrise.github.io#1]
https://amazingrise.github.io/2019/04/20/Manjaro-Optimus-Dual-Monitor/ 

 前言很久之前，就给自己新买的笔记本装上了Manjaro。可惜由于笔记本是双显卡，总会有些奇奇怪怪的问题。（参见下文题外话，关于Windows 10上双显卡的“优秀表现”）Manjaro上的问题就是，无法识别外置显示器，只能搁置。看着黑的发亮的显示器，真是十分让人恼火。想用 Linux 怎么办？ 只能装上 Ubuntu 了事。真香Ubuntu 上不需要修改任何设置，直接就能识别外接显示器。后来经过一

**Comment by AmazingRise** [comment]
欢迎大家登录GitHub账号评论！

**Comment by vvvxo** [comment]
在安装Nvidia驱动时，如果使用-a参数可能安装失败，这时可以尝试使用-i参数

**Comment by zangwill** [comment]
如果`lspci | grep -E "VGA|3D"`输出：
```sh
00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
02:00.0 3D controller: NVIDIA Corporation GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M] (rev ff)
```
那么BusID是不是设置成`"PCI:2:0:0"`

**Comment by zangwill** [comment]
> @AmazingRise

附议，使用 -a 参数输出语法错误：
```sh
sudo mhwd -a pci video-nvidia-390xx
[sudo] zw 的密码：
Error: invalid use of option: -a/--auto
```
改为 -i 参数可以正常安装：
```sh
sudo mhwd -i pci video-nvidia-390xx
> Installing video-nvidia-390xx...
Sourcing /etc/mhwd-x86_64.conf
Has lib32 support: true
...
```

**Comment by AmazingRise** [comment]
> @Zangwill
> > @AmazingRise
> 
> 附议，使用 -a 参数输出语法错误：
> ```sh
> sudo mhwd -a pci video-nvidia-390xx
> [sudo] zw 的密码：
> Error: invalid use of option: -a/--auto
> ```
> 改为 -i 参数可以正常安装：
> ```sh
> sudo mhwd -i pci video-nvidia-390xx
> > Installing video-nvidia-390xx...
> Sourcing /etc/mhwd-x86_64.conf
> Has lib32 support: true
> ...
> ```
> 

感谢反馈~
是我疏忽了，的确应该是-i，十分感谢，待会修改一下

**Comment by AmazingRise** [comment]
> @Zangwill
> 如果`lspci | grep -E "VGA|3D"`输出：
> ```sh
> 00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
> 02:00.0 3D controller: NVIDIA Corporation GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M] (rev ff)
> ```
> 那么BusID是不是设置成`"PCI:2:0:0"`

是的，需要按照具体情况设置的。我再加一些详细的说明，非常感谢~

**Comment by jnzhanghs** [comment]
按照PRIME来做双显示器是没问题，但是不能hibernate，不禁用nvidiafb可以hibernate，无法resume。博主碰到过没

**Comment by AmazingRise** [comment]
> @jnzhanghs
> 按照PRIME来做双显示器是没问题，但是不能hibernate，不禁用nvidiafb可以hibernate，无法resume。博主碰到过没

我无论是否禁用nvidiafb都有一定几率无法正常唤醒。最后用journalctl -b查了一下日志，翻了翻Google，发现是nvidia私有驱动的问题。而且还是个老bug。这个暂时没有解决方案QAQ

**Comment by unixjx** [comment]
niubility，非常感谢

**Comment by AlwaysStudent** [comment]
博主大大，我使用的系统镜像版本为``gnome-18.1.0-stable``
在使用开源驱动时进入系统可以识别到显示器，但是在安装更新之后显示器会出现花屏的情况
而使用闭源驱动则从始至终都无法识别到显示器
我的显卡型号为``1060-mq``，在``BIOS``中没有禁用选项
希望博主可以给予我一些帮助

**Comment by AmazingRise** [comment]
> @AlwaysStudent
> 博主大大，我使用的系统镜像版本为``gnome-18.1.0-stable``
> 在使用开源驱动时进入系统可以识别到显示器，但是在安装更新之后显示器会出现花屏的情况
> 而使用闭源驱动则从始至终都无法识别到显示器
> 我的显卡型号为``1060-mq``，在``BIOS``中没有禁用选项
> 希望博主可以给予我一些帮助

如果我没记错的话,之前我遇到的情况和你是一样的.
开源驱动能检测到但花屏,闭源驱动没法识别显示器.
只要照着这篇文章的解决方法做就好啦~没问题的!

**Comment by KEIR-ECIR2025** [comment]
连接显卡坞的情况似乎没有效果。
感谢分享，但是我这台机器不太有用。
我用的是thinkpad x1 carbon 2019，连接了雷蛇战核X，外接显示器用HDMI连上了显卡。
我按照分享里面步骤操作了多次，终究是没有成功。
最后只能卡在联想logo，能进入tty命令行界面，但是进不了系统。
哎，太遗憾了，用不了多屏manjaro！

**Comment by xiangjs6** [comment]
博主你好，我的笔记本用的manjaro kde装好了独显驱动，但是桌面锁屏后，会有几率导致会话退出；并且把外接显示器设置为主显示器后，重启会使得一些窗口飞到笔记本的显示器上，本来应该在外接显示器上的

**Comment by WarrenYang99** [comment]
博主大大，我用的kde的桌面，按照你的步骤装完之后只有外屏亮是怎么回事撒。。。。

**Comment by AmazingRise** [comment]
> 博主大大，我用的kde的桌面，按照你的步骤装完之后只有外屏亮是怎么回事撒。。。。

如果是这样的话，说明你只安装好了独显驱动。后面配置文件那个地方还是有问题，再找找看

**Comment by AmazingRise** [comment]
其他问题请在新的评论区评论，谢谢合作。

**Comment by ChenSino** [comment]
![image](https://user-images.githubusercontent.com/25560521/103452191-97186400-4d07-11eb-9a09-344d5f326a29.png)
设置好了没有啥用啊，我也是笔记本双显卡，外置的HDMI显示屏不行，外置屏幕一直闪烁，亮一下 然后黑屏很久，然后又亮……我没按照你这样设置前也是同样的现象。  用414的内核可以双屏，不过CPU消耗很严重，
